pointPath = "../data/squarepoints.txt"
searchRadius = 1.1

# [kuramoto]
# outfile = "kuramoto.txt"
# K = 1.01
# N = 10
# t = {start = 0, end = 100, n = 10000}
#
# [basic]
# pointPath = "../data/mediummonotilepoints.txt"
# # pointPath = "../data/smallermonotilepoints.txt"
# outfile = "basic.h5"
# t = {start = 0, end = 100, n = 10000}
# # searchRadius = "auto"

[tetm]
outfile = "tetm.h5"
alpha = 1
p = 2
pointPath = "../data/smallermonotilepoints.txt"
t = {start = 0, end = 100, n = 1000}
