pointPath = "../data/squarepoints.txt"
searchRadius = 1.1

# [kuramoto]
# outfile = "kuramoto.txt"
# K = 1.01
# N = 10
# t = {start = 0, end = 100, n = 10000}
#
# [basic]
# pointPath = "../data/mediummonotilepoints.txt"
# # pointPath = "../data/smallermonotilepoints.txt"
# outfile = "basic.h5"
# t = {start = 0, end = 100, n = 10000}
# # searchRadius = "auto"

# [tetm]
# outfile = "monotetm.h5"
# alpha = 1
# p = 0.10277136
# j = 0.01
# searchRadius = 0.584
# pointPath = "../data/bettermonotilepts.txt"
# t = { start = 0, end = 1000, n = 100000 }

[basicdistance]
outfile = "distancescan.h5"
alpha = 1
p = 1
sep = { start = 10, end = 20, n = 1000 }
t = { start = 0, end = 100, n = 14096 }
