pointPath = "../data/squarepoints.txt"
searchRadius = 1.1

# [kuramoto]
# outfile = "kuramoto.txt"
# K = 1.01
# N = 10
# t = {start = 0, end = 100, n = 10000}
#
# [basic]
# pointPath = "../data/mediummonotilepoints.txt"
# # pointPath = "../data/smallermonotilepoints.txt"
# outfile = "basic.h5"
# t = {start = 0, end = 100, n = 10000}
# # searchRadius = "auto"

[basichankeldd]
outfile = "tetrilledd.h5"
alpha = 1
p = 0.10277136
j = 0.1
searchRadius = 1.74
pointPath = "../data/tetrilles/smallertetrille.txt"
t = { start = 0, end = 1000, n = 100000 }

[basicdistance]
outfile = "distancescanloweralpha.h5"
alpha = 8
p = 1
j = 10
sep = { start = 5, end = 40, n = 1000 }
t = { start = 0, end = 480, n = 11024 }
