[calcs]
do2D = false
doPath = true 

[lattice]
points = [
  [0, 0],
  [0, 1.73205080757],
  [-1, 1.73205080757],
  [-1.5, 0.86602540378],
  [-2, 0],
  [-1.5, -0.86602540378],
]

lat_vecs = [
  [3, -1.7320508757],
  [3, 1.7320508757],
]

connections = [
  {source = 0, destinations=[ [1, 0, 0], [3, 0, 0], [5, 0, 0], [3, 1, 0], [5, 0, 1], [1, 1, -1] ] },
  {source = 1, destinations = [[2, 0, 0], [4, 0, 1]]},
  {source = 2, destinations = [[3, 0, 0], [5, -1, 1]]},
  {source = 3, destinations = [[4, 0, 0]]},
  {source = 4, destinations = [[5, 0, 0]]},
]

[grid]
[grid.kxrange]
start = -100
end = 100
n = 800

[grid.kyrange]
start = -100
end = 100
n = 800

[path]
ranges = [
  {start = [0, 0], end = [0, 0.5], n = 100},
  {start = [0, 0.5], end = [1, 0.5], n = 100},
  {start = [1, 0.5], end = [1, 1], n = 100},
]
